insert into public.biomarker_catalog(slug, display_name, category, canonical_unit, aliases) values
('hematies','Hématies','Hématologie','T/L',array['Hématies','Hematies','Globules rouges','RBC']),
('hematocrite','Hématocrite','Hématologie','%',array['Hématocrite','Hematocrite','HCT']),
('vgm','VGM','Hématologie','fL',array['V.G.M','VGM','MCV']),
('tcmh','TCMH','Hématologie','pg',array['T.C.M.H','TCMH','MCH']),
('ccmh','CCMH','Hématologie','g/dL',array['C.C.M.H','CCMH','MCHC']),
('neutrophiles','Neutrophiles','Hématologie','G/L',array['Polynucléaires neutrophiles','Polynucleaires neutrophiles','Neutrophiles','Neutrophils']),
('eosinophiles','Éosinophiles','Hématologie','G/L',array['Polynucléaires éosinophiles','Polynucleaires eosinophiles','Éosinophiles','Eosinophiles','Eosinophils']),
('basophiles','Basophiles','Hématologie','G/L',array['Polynucléaires basophiles','Polynucleaires basophiles','Basophiles','Basophils']),
('lymphocytes','Lymphocytes','Hématologie','G/L',array['Lymphocytes','Lymphocyte']),
('monocytes','Monocytes','Hématologie','G/L',array['Monocytes','Monocyte']),
('myelemie','Myélémie','Hématologie','%',array['Myélémie','Myelemie','Immatures gran.','Granulocytes immatures']),
('erythroblastes','Érythroblastes','Hématologie','%',array['Erythroblastes','Érythroblastes','NRBC']),
('fer','Fer','Fer','µmol/L',array['Fer','Fer sérique','Fer serique','Iron']),
('transferrine','Transferrine','Fer','g/L',array['Transferrine','Transferrin']),
('capacite_totale_fixation','Capacité totale de fixation','Fer','µmol/L',array['Capacité totale de fixation','Capacite totale de fixation','CTF','TIBC']),
('saturation_transferrine','Saturation de la transferrine','Fer','%',array['Coefficient de saturation','CS-TF','Saturation transferrine','Transferrin saturation']),
('sodium','Sodium','Électrolytes','mmol/L',array['Sodium','Na+']),
('potassium','Potassium','Électrolytes','mmol/L',array['Potassium sérique','Potassium serique','Potassium','K+']),
('chlore','Chlore','Électrolytes','mmol/L',array['Chlore','Chlorure','Chloride']),
('calcium','Calcium','Électrolytes','mmol/L',array['Calcium','Calcémie','Calcemie']),
('calcium_corrige','Calcium corrigé','Électrolytes','mmol/L',array['Calcium corrigé','Calcium corrige','Corrected calcium']),
('phosphore','Phosphore','Électrolytes','mmol/L',array['Phosphore','Phosphate','Phosphorus']),
('phosphatases_alcalines','Phosphatases alcalines','Foie','U/L',array['Phosphatases alcalines','Phosphatase alcaline','ALP']),
('albumine','Albumine','Protéines','g/L',array['Albumine','Albumin']),
('lipase','Lipase','Pancréas','U/L',array['Lipase'])
on conflict (slug) do update
set display_name = excluded.display_name,
    category = excluded.category,
    canonical_unit = excluded.canonical_unit,
    aliases = excluded.aliases;
